[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "foundry-devops/=lib/foundry-devops/",
  "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
  "chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/"
]


ffi= true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
